package semantic_errors;

public enum SemanticErrorType {
    MISSING_FLASK_VARIABLE,
    INVALID_FUNC_CALL,
    WRONG_ARGS_COUNT,
    RETURN_TYPE_MISMATCH,
    TYPE_MISMATCH,
    DIVISION_BY_ZERO,
    UNBOUND_LOCAL,
    USE_BEFORE_INIT,

}
